whoami: Глеб Гончаров
title: Сайт Глеба Гончарова
description: Системный администратор в ФанБоксе. Автоматизирую и сопровождаю инфраструктуру для проектов мобильных операторов.
email: inbox@gongled.ru
baseurl: ""
url: "https://gongled.ru"
lang: ru

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Sass settings
sass:
    style: :compressed

analytics:
  google:
    tracking_code: UA-89780216-1
  yandex:
    tracking_code: 24643331

contacts:
  googleplus: GlebGoncharov
  github: gongled
  twitter: gongled
  instagram: gongled
  facebook: gongled
  vk: gongled
  linkedin: gongled
  telegram: gongled

paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  pages:
    output: true
    permalink: :path

# Defaults
defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title.html
  - scope:
      type: pages
    values:
      layout: page

exclude: [vendor, deploy.yml, environments, Gemfile, Gemfile.lock, Makefile, README.md, deploy.retry, Dockerfile, docker-compose.yml, ansible.cfg]
