baseURL = "https://gon.gl/"
languageCode = "ru-ru"
title = "Сайт Глеба Гончарова"
theme = "simple"
avatar = "userpic.jpg"
staticDir = ["static"]

[build]
  writeStats = true

[permalinks]
  blog = "/blog/:filename/"
  work = "/work/:filename/"

[params]
  author = "Глеб Гончаров"
  description = "Системный администратор в ФанБоксе. Автоматизирую и сопровождаю инфраструктуру для проектов мобильных операторов."
  email = "inbox@gon.gl"
  videoURL = "https://static.gon.gl/video/"
  nickname = "gongled"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4