---

- name: Deployment 
  hosts: app
  vars_files:
    - "environments/{{ env }}/group_vars/project.yml"
  tasks:
    - name: deploy application to working directory
      become: no
      synchronize:
        src: "public/"
        dest: "{{ app.path }}/"
        archive: yes
        delete: yes
        recursive: yes
