version: "3"
services:
  app:
    build:
      context: .
    command: hugo server
    expose:
      - 1313
    ports:
      - 1313:1313
    volumes:
      - .:/app
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
